# Завдання на використання SQL в Python

In [1]:
!pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-8.4.0-cp310-cp310-manylinux_2_17_x86_64.whl (19.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 37.1 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-8.4.0

In [14]:
import mysql.connector
from mysql.connector.connection import MySQLConnection
import datetime
import pandas as pd
from sqlalchemy import create_engine

In [40]:
con = mysql.connector.connect(user='user1', password='7oygWy6P',
                              host='3.68.62.36',
                              database='employees')

1. **З'єднання таблиць "employees" та "salaries"**

 Виведіть список з 10 співробітників, їх emp_no, first_name, last_name та їхню поточну зарплату. В даному випадку порядок співробіників не має значення, суть в тому аби отримати правильну структуру таблиці.

In [4]:
cursor = con.cursor()

query = """
SELECT
    e.emp_no,
    e.first_name,
    e.last_name,
    s.salary
FROM
    employees e
    INNER JOIN salaries s ON e.emp_no = s.emp_no
WHERE
    s.to_date = '9999-01-01'
LIMIT 10;
"""

cursor.execute(query)

result = cursor.fetchall()

cursor.close()

df = pd.DataFrame(result, columns=['emp_no', 'first_name', 'last_name', 'salary'])

In [5]:
df

   emp_no first_name  last_name  salary
0   10001     Georgi    Facello   88958
1   10002    Bezalel     Simmel   72527
2   10003      Parto    Bamford   43311
3   10004  Chirstian    Koblick   74057
4   10005    Kyoichi   Maliniak   94692
5   10006     Anneke    Preusig   59755
6   10007    Tzvetan  Zielinski   88070
7   10009     Sumant       Peac   94409
8   10010  Duangkaew   Piveteau   80324
9   10012   Patricio  Bridgland   54423

2. **З'єднання таблиць "employees" та "titles"**
    
    Виведіть список з 10 співробітників, їх **`emp_no`**, **`first_name`**, **`last_name`** та їхню **поточну** **посаду**. В даному випадку порядок співробіників не має значення, суть в тому аби отримати правильну структуру таблиці.

In [6]:
cursor = con.cursor()

query = """
SELECT
    e.emp_no,
    e.first_name,
    e.last_name,
    t.title
FROM
    employees e
    INNER JOIN titles t ON e.emp_no = t.emp_no
WHERE
    t.to_date = '9999-01-01'
LIMIT 10;
"""

cursor.execute(query)

result = cursor.fetchall()

cursor.close()

df = pd.DataFrame(result, columns=['emp_no', 'first_name', 'last_name', 'title'])

In [7]:
df

   emp_no first_name  last_name            title
0   10001     Georgi    Facello  Senior Engineer
1   10002    Bezalel     Simmel            Staff
2   10003      Parto    Bamford  Senior Engineer
3   10004  Chirstian    Koblick  Senior Engineer
4   10005    Kyoichi   Maliniak     Senior Staff
5   10006     Anneke    Preusig  Senior Engineer
6   10007    Tzvetan  Zielinski     Senior Staff
7   10009     Sumant       Peac  Senior Engineer
8   10010  Duangkaew   Piveteau         Engineer
9   10012   Patricio  Bridgland  Senior Engineer

3. **З'єднання таблиць "employees", "dept_emp" та "departments"**

 Виведіть список з 10 співробітників, їх emp_no, first_name, last_name та відділ, де вони зараз працюють. В даному випадку порядок співробіників не має значення, суть в тому аби отримати правильну структуру таблиці.

In [16]:
cursor = con.cursor()

query = """
SELECT
    e.emp_no,
    e.first_name,
    e.last_name,
    d.dept_name
FROM
    employees e
    INNER JOIN dept_emp de ON e.emp_no = de.emp_no
    INNER JOIN departments d ON de.dept_no = d.dept_no
WHERE
    de.to_date = '9999-01-01'
LIMIT 10;
"""

cursor.execute(query)

result = cursor.fetchall()

cursor.close()

df = pd.DataFrame(result, columns=['emp_no', 'first_name', 'last_name', 'dept_name'])

In [17]:
df

   emp_no first_name    last_name         dept_name
0   10038       Huan        Lortz  Customer Service
1   10049      Basil       Tramer  Customer Service
2   10060   Breannda  Billingsley  Customer Service
3   10088   Jungsoon     Syrzycki  Customer Service
4   10112   Yuichiro        Swick  Customer Service
5   10126     Kayoko     Valtorta  Customer Service
6   10128    Babette        Lamba  Customer Service
7   10137      Maren       Hutton  Customer Service
8   10154    Abdulah    Thibadeau  Customer Service
9   10164     Jagoda    Braunmuhl  Customer Service

4. Керівництво вашої компанії прагне отримати чітке розуміння щодо розподілу працівників між різними відділами. Специфічно, потрібно:
    - Визначити кількість унікальних працівників у кожному відділі.
    - Представити цю інформацію у впорядкованому вигляді, починаючи з відділу з найбільшою кількістю працівників.
    
  Для цієї задачі вам потрібні таблиці
    
    - `departments`, яка містить інформацію про відділи (включаючи `dept_name` та `dept_no`),
    - і `dept_emp`, яка містить відомості про приналежність працівників до відділів (включаючи `emp_no` та `dept_no`).

In [18]:
cursor = con.cursor()

query = """
SELECT
    d.dept_name,
    COUNT(DISTINCT de.emp_no) AS num_employees
FROM
    departments d
    INNER JOIN dept_emp de ON d.dept_no = de.dept_no
GROUP BY
    d.dept_name
ORDER BY
    num_employees DESC;
"""

cursor.execute(query)

result = cursor.fetchall()

cursor.close()

df = pd.DataFrame(result, columns=['dept_name', 'num_employees'])

In [19]:
df

            dept_name  num_employees
0         Development          85707
1          Production          73485
2               Sales          52245
3    Customer Service          23580
4            Research          21126
5           Marketing          20211
6  Quality Management          20117
7     Human Resources          17786
8             Finance          17346

5. Знайдіть, хто є найбільш високооплачуваним працівником у відділі Development. Вам потрібно визначити ідентифікаційний номер, ім'я, прізвище та зарплату цього працівника.

In [20]:
cursor = con.cursor()

query = """
SELECT
    e.emp_no,
    e.first_name,
    e.last_name,
    s.salary
FROM
    employees e
    INNER JOIN dept_emp de ON e.emp_no = de.emp_no
    INNER JOIN departments d ON de.dept_no = d.dept_no
    INNER JOIN salaries s ON e.emp_no = s.emp_no
WHERE
    d.dept_name = 'Development' AND
    s.to_date = '9999-01-01' AND
    de.to_date = '9999-01-01'
ORDER BY
    s.salary DESC
LIMIT 1;
"""

cursor.execute(query)

result = cursor.fetchone()

cursor.close()

df = pd.DataFrame([result], columns=['emp_no', 'first_name', 'last_name', 'salary'])

In [21]:
df

   emp_no first_name last_name  salary
0   13386    Khosrow    Sgarro  144434

6. Ми хочемо визначити, в якому відділі працює найбільш високооплачуваний співробітник в компанії. Виведіть його ідентифікаційний номер, ім'я, прізвище, зарплату та відділ.

In [22]:
cursor = con.cursor()

query = """
SELECT
    e.emp_no,
    e.first_name,
    e.last_name,
    s.salary,
    d.dept_name
FROM
    employees e
    INNER JOIN salaries s ON e.emp_no = s.emp_no
    INNER JOIN dept_emp de ON e.emp_no = de.emp_no
    INNER JOIN departments d ON de.dept_no = d.dept_no
WHERE
    s.to_date = '9999-01-01' AND
    de.to_date = '9999-01-01'
ORDER BY
    s.salary DESC
LIMIT 1;
"""

cursor.execute(query)

result = cursor.fetchone()

cursor.close()

df = pd.DataFrame([result], columns=['emp_no', 'first_name', 'last_name', 'salary', 'dept_name'])

In [23]:
df

   emp_no first_name last_name  salary dept_name
0   43624   Tokuyasu     Pesch  158220     Sales

7. Виведіть номер, імʼя, прізвище і розмір зарплати співробітника з **третьою** найвищою зарплатою (тобто якщо б ми відсотували співробітників за спаданням ЗП, цей був би третім в списку). Треба вивести лише один рядок даних.
    
    **Підказка:** тут можна використати функціонал LIMIT. Ми продовжуємо занурюватись в SQL, і насправді LIMIT може приймати 2 аргументи - перший - це так званий offcet, другий - кількість рядків. Детальніше - за [посиланням](https://dev.mysql.com/doc/refman/8.0/en/select.html)

In [24]:
cursor = con.cursor()

query = """
SELECT
    e.emp_no,
    e.first_name,
    e.last_name,
    s.salary
FROM
    employees e
    INNER JOIN salaries s ON e.emp_no = s.emp_no
WHERE
    s.to_date = '9999-01-01'
ORDER BY
    s.salary DESC
LIMIT 2, 1;
"""

cursor.execute(query)

result = cursor.fetchone()

cursor.close()

df = pd.DataFrame([result], columns=['emp_no', 'first_name', 'last_name', 'salary'])

In [25]:
df

   emp_no first_name last_name  salary
0   47978     Xiahua  Whitcomb  155709

8. **Знайдіть співробітників з декількома посадами**
    
    Деякі співробітники можуть змінювати свої посади протягом роботи в компанії. Визначте всіх співробітників, які мали більше однієї посади за час роботи в компанії. Відобразіть їх `emp_no`, `first_name`, `last_name` та список всіх посад, на яких вони працювали.
    
    **Підказка:** Для цього потрібно зробити join таблиці `titles` до `employees`. Для того аби сконкатенувати кілька назв позицій можна використати агрегаційну функцію GROUP_CONCAT.

In [26]:
cursor = con.cursor()

query = """
SELECT
    e.emp_no,
    e.first_name,
    e.last_name,
    GROUP_CONCAT(DISTINCT t.title ORDER BY t.title SEPARATOR ', ') AS titles
FROM
    employees e
    INNER JOIN titles t ON e.emp_no = t.emp_no
GROUP BY
    e.emp_no,
    e.first_name,
    e.last_name
HAVING
    COUNT(DISTINCT t.title) > 1;
"""

cursor.execute(query)

results = cursor.fetchall()

cursor.close()

df = pd.DataFrame(results, columns=['emp_no', 'first_name', 'last_name', 'titles'])

In [27]:
df

,emp_no,first_name,last_name,titles
0,10004,Chirstian,Koblick,"Engineer, Senior Engineer"
1,10005,Kyoichi,Maliniak,"Senior Staff, Staff"
2,10007,Tzvetan,Zielinski,"Senior Staff, Staff"
3,10009,Sumant,Peac,"Assistant Engineer, Engineer, Senior Engineer"
4,10012,Patricio,Bridgland,"Engineer, Senior Engineer"
...,...,...,...,...
140265,499988,Bangqing,Kleiser,"Senior Staff, Staff"
140266,499992,Siamak,Salverda,"Senior Staff, Staff"
140267,499996,Zito,Baaz,"Engineer, Senior Engineer"
140268,499997,Berhard,Lenart,"Engineer, Senior Engineer"
140269,499998,Patricia,Breugel,"Senior Staff, Staff"

9. **Переводи між відділами**
    
    Співробітники іноді переходять між відділами. Визначте всіх співробітників, які працювали в більш ніж одному відділі. Відобразіть їх `emp_no`, `first_name`, `last_name` та назви всіх відділів, в яких вони працювали.
    
    **Підказка:** Вам потрібно буде приєднати таблиці `employees`, `dept_emp` та `departments` та, можливо, використовувати self join `dept_emp`.

In [28]:
cursor = con.cursor()

query = """
SELECT
    e.emp_no,
    e.first_name,
    e.last_name,
    GROUP_CONCAT(DISTINCT d.dept_name ORDER BY d.dept_name SEPARATOR ', ') AS departments
FROM
    employees e
    INNER JOIN dept_emp de ON e.emp_no = de.emp_no
    INNER JOIN departments d ON de.dept_no = d.dept_no
GROUP BY
    e.emp_no,
    e.first_name,
    e.last_name
HAVING
    COUNT(DISTINCT d.dept_no) > 1;
"""

cursor.execute(query)

results = cursor.fetchall()

cursor.close()

df = pd.DataFrame(results, columns=['emp_no', 'first_name', 'last_name', 'departments'])

In [29]:
df

       emp_no    first_name last_name                     departments
0       10010     Duangkaew  Piveteau  Production, Quality Management
1       10018      Kazuhide      Peha         Development, Production
2       10029         Otmar    Herbst  Production, Quality Management
3       10040         Weiyi   Meriste           Development, Research
4       10050       Yinghua    Dredge                  Finance, Sales
...       ...           ...       ...                             ...
31574  499955  Kankanahalli    Zucker   Customer Service, Development
31575  499964         Randy    Matzov  Production, Quality Management
31576  499975        Masali   Chorvat        Finance, Human Resources
31577  499983           Uri    Juneja    Customer Service, Production
31578  499992        Siamak  Salverda      Human Resources, Marketing

[31579 rows x 4 columns]

10. **Поточна зарплата керівника (задача з зірочкою)**
    
    Для кожного відділу вкажіть назву відділу, `emp_no` поточного керівника, його `first_name`, `last_name` та поточну зарплату. Переконайтеся, що ви отримуєте саме **поточну** зарплату **поточного** керівника.
    
    **Підказка:** Вам потрібно буде заджойнити декілька таблиць, включаючи `departments`, `dept_manager`, `employees` та `salaries`. Не забудьте відфільтрувати найновішу дату зарплати для кожного керівника. Тут може бути зручно скористатись конструкцією [WITH](https://dev.mysql.com/doc/refman/8.0/en/with.html) або створити підзапит.

In [34]:
cursor = con.cursor()

query = """
SELECT
    t.dept_name,
    t.emp_no,
    t.first_name,
    t.last_name,
    s.salary
FROM
    (SELECT
        d.dept_name,
        dm.emp_no,
        e.first_name,
        e.last_name,
        MAX(from_date) as from_date,
        MAX(to_date) as to_date
    FROM departments d
    JOIN
        dept_manager dm ON d.dept_no=dm.dept_no
    JOIN
        employees e ON dm.emp_no=e.emp_no
    GROUP BY
        d.dept_name,
        dm.emp_no,
        e.first_name,
        e.last_name
    HAVING
        to_date = '9999-01-01') t
JOIN
    salaries s ON t.emp_no = s.emp_no
                AND s.to_date = '9999-01-01'
GROUP BY
    t.dept_name,
    t.emp_no,
    t.first_name,
    t.last_name,
    s.from_date,
    s.to_date,
    s.salary
HAVING
    s.from_date = MAX(s.from_date)
"""

cursor.execute(query)

results = cursor.fetchall()

cursor.close()

df = pd.DataFrame(results, columns=['dept_name', 'emp_no', 'first_name', 'last_name', 'salary'])

In [35]:
df

            dept_name  emp_no first_name   last_name  salary
0    Customer Service  111939    Yuchang     Weedman   58745
1         Development  110567       Leon    DasSarma   74510
2             Finance  110114      Isamu  Legleitner   83457
3     Human Resources  110228    Karsten     Sigstam   65400
4           Marketing  110039   Vishwani    Minakawa  106491
5          Production  110420      Oscar    Ghazalie   56654
6  Quality Management  110854       Dung       Pesch   72876
7            Research  111534     Hilary      Kambil   79393
8               Sales  111133      Hauke       Zhang  101987

**Завдання на використання Window Functions**

Window functions час від часу бувають на співбесідах і зустрічаються в роботі. Не так часто як джойни, але їх теж варто знати.

[Стаття](https://towardsdatascience.com/a-guide-to-advanced-sql-window-functions-f63f2642cbf9) в якій детально і доступно пояснено про window functions. Вона велика, але після її прочитання і прктики - ви добре засвоїте матеріал.

[Документація](https://dev.mysql.com/doc/refman/8.0/en/window-functions-usage.html) MySQL по Window functions.

Всього 7 завдань. 4 легких і 3 середніх. В завданні написано, яку функцію треба використати. Часто буде зручно використати WITH частину.

1. **Використання ROW_NUMBER**
Для перших 10 співробітників (за `emp_no`) виведіть їх `emp_no`, `first_name`, `last_name`, а також порядковий номер співробітника в таблиці.

In [43]:
cursor = con.cursor()

query = """
SELECT emp_no, first_name, last_name,
       ROW_NUMBER() OVER (ORDER BY emp_no) as row_num
FROM employees
LIMIT 10;
"""

cursor.execute(query)

results = cursor.fetchall()

cursor.close()

df = pd.DataFrame(results, columns=['emp_no', 'first_name', 'last_name', 'row_num'])

In [44]:
df

   emp_no first_name  last_name  row_num
0   10001     Georgi    Facello        1
1   10002    Bezalel     Simmel        2
2   10003      Parto    Bamford        3
3   10004  Chirstian    Koblick        4
4   10005    Kyoichi   Maliniak        5
5   10006     Anneke    Preusig        6
6   10007    Tzvetan  Zielinski        7
7   10008     Saniya   Kalloufi        8
8   10009     Sumant       Peac        9
9   10010  Duangkaew   Piveteau       10

2. **Вивести зарплатну динаміку співробітника**
Виведіть `emp_no`, дату початку (`from_date`), зарплату та попереднє значення зарплати для співробітника з `emp_no = 10001`.
    
    **Підказка:** скористайтеся функцією LAG

In [47]:
cursor = con.cursor()

query = """
SELECT emp_no, from_date, salary,
       LAG(salary) OVER (ORDER BY from_date) AS previous_salary
FROM salaries
WHERE emp_no = 10001
ORDER BY from_date;

"""

cursor.execute(query)

results = cursor.fetchall()

cursor.close()

df = pd.DataFrame(results, columns=['emp_no', 'from_date', 'salary', 'prev_salary'])

In [48]:
df

    emp_no   from_date  salary  prev_salary
0    10001  1986-06-26   60117          NaN
1    10001  1987-06-26   62102      60117.0
2    10001  1988-06-25   66074      62102.0
3    10001  1989-06-25   66596      66074.0
4    10001  1990-06-25   66961      66596.0
5    10001  1991-06-25   71046      66961.0
6    10001  1992-06-24   74333      71046.0
7    10001  1993-06-24   75286      74333.0
8    10001  1994-06-24   75994      75286.0
9    10001  1995-06-24   76884      75994.0
10   10001  1996-06-23   80013      76884.0
11   10001  1997-06-23   81025      80013.0
12   10001  1998-06-23   81097      81025.0
13   10001  1999-06-23   84917      81097.0
14   10001  2000-06-22   85112      84917.0
15   10001  2001-06-22   85097      85112.0
16   10001  2002-06-22   88958      85097.0

3. **Визначення рангу зарплати в межах відділу**
Виведіть `emp_no`, `dept_name`, поточну зарплату та ранг співробітника в межах його відділу за розміром зарплати.
    
    **Підказка:** скористайтеся функцією RANK

In [53]:
cursor = con.cursor()

query = """
SELECT
    e.emp_no,
    d.dept_name,
    s.salary,
       RANK() OVER (PARTITION BY de.dept_no ORDER BY s.salary DESC) as salary_rank
FROM
    employees e
JOIN
    salaries s ON e.emp_no = s.emp_no
JOIN
    dept_emp de ON e.emp_no = de.emp_no
JOIN departments d ON de.dept_no = d.dept_no
WHERE
    s.to_date = '9999-01-01'
LIMIT 10;
"""

cursor.execute(query)

results = cursor.fetchall()

cursor.close()

df = pd.DataFrame(results, columns=['emp_no', 'dept_name', 'salary', 'salary_rank'])

In [54]:
df

   emp_no  dept_name  salary  salary_rank
0  466852  Marketing  145128            1
1   89825  Marketing  143644            2
2  107140  Marketing  142506            3
3   80937  Marketing  142485            4
4   51531  Marketing  141842            5
5  102078  Marketing  140974            6
6  477358  Marketing  140077            7
7  278498  Marketing  138755            8
8  235645  Marketing  138637            9
9  475041  Marketing  137413           10

4. **Знаходження зміни зарплати співробітника протягом останніх 2 років**

 Виведіть різницю між поточною зарплатою співробітника з emp_no = 10001 та його зарплатою 2 роки тому. Формат відповіді: номер співробітника, salary_2_years_ago, поточна ЗП, різниця у зарплатах 2 роки тому і зараз.

In [59]:
cursor = con.cursor()

query = """
SELECT s.emp_no,
       LAG(salary, 2) OVER (ORDER BY from_date) as salary_2_years_ago,
       salary,
       salary - LAG(salary, 2) OVER (ORDER BY from_date) as salary_difference
FROM salaries s
WHERE
    s.emp_no = 10001
ORDER BY from_date DESC
LIMIT 1;
"""

cursor.execute(query)

results = cursor.fetchall()

cursor.close()

df = pd.DataFrame(results, columns=['emp_no', 'salary_2_years_ago', 'salary', 'salary_difference'])

In [60]:
df

   emp_no  salary_2_years_ago  salary  salary_difference
0   10001               85112   88958               3846

5. **Визначення найвищого зростання зарплати**

 Знайдіть співробітника, який отримав найбільше збільшення зарплати протягом року, який закінчився 1 рік до найновішої дати в базі даних (максимальне значення from_date в таблиці salaries). Формат відповіді: номер співробітника, ЗП з попереднього року, поточка ЗП, на яку суму змінилась ЗП.

In [64]:
cursor = con.cursor()

query = """
WITH MaxDate AS (
    SELECT MAX(from_date) AS latest_date FROM salaries
),
SalaryDifference AS (
    SELECT s.emp_no,
           LAG(salary) OVER (PARTITION BY
              s.emp_no ORDER BY from_date) AS prev_salary,
           salary,
           salary - LAG(salary) OVER (PARTITION BY
              s.emp_no ORDER BY from_date) AS diff,
           from_date
    FROM salaries s
    JOIN MaxDate
    ON s.from_date BETWEEN DATE_SUB(latest_date, INTERVAL 2 YEAR)
                      AND DATE_SUB(latest_date, INTERVAL 1 YEAR)
)
SELECT emp_no, prev_salary, salary, MAX(diff) AS max_difference
FROM SalaryDifference
GROUP BY
    emp_no,
    prev_salary,
    salary
ORDER BY
    max_difference DESC
LIMIT 1;
"""

cursor.execute(query)

results = cursor.fetchall()

cursor.close()

df = pd.DataFrame(results, columns=['emp_no', 'prev_salary', 'salary', 'max_difference'])

In [65]:
df

   emp_no  prev_salary  salary  max_difference
0  278208        68917   73416            4499

6. **Середня зарплата та перший праціник на кожній посаді**

 Для кожної посади виведіть її назву, середню зарплату співробітників на ній, ім'я першого співробітника (або співробітників, якщо в один і той самий день було прийнято на цю посаду кілька людей), який був прийнятий на цю посаду (згідно дати прийому на роботу - hire_date), а також hire_date цього співробітника чи співробітників. У відповіді відсортуйте результати за назвою посади і імʼям співробітника.

In [71]:
cursor = con.cursor()

query = """
WITH AverageSalary AS (
    SELECT
        t.title,
        AVG(s.salary) as avg_salary
    FROM
        titles t
    JOIN
        salaries s ON t.emp_no = s.emp_no
    WHERE
        t.to_date = '9999-01-01' AND s.to_date = '9999-01-01'
    GROUP BY
        t.title
),
EarliestHire AS (
    SELECT
        t.title,
        MIN(e.hire_date) as earliest_hire_date
    FROM
        titles t
    JOIN
        employees e ON t.emp_no = e.emp_no
    WHERE
        t.to_date = '9999-01-01'
    GROUP BY
        t.title
)

SELECT
    a.title,
    a.avg_salary,
    e.first_name,
    eh.earliest_hire_date
FROM
    AverageSalary a
JOIN
    EarliestHire eh ON a.title = eh.title
JOIN
    titles t ON eh.title = t.title
JOIN
    employees e ON t.emp_no = e.emp_no AND eh.earliest_hire_date = e.hire_date
WHERE
    t.to_date = '9999-01-01'
ORDER BY
    title, first_name;

"""

cursor.execute(query)

results = cursor.fetchall()

cursor.close()

df = pd.DataFrame(results, columns=['title', 'prev_salary', 'first_name', 'last_hire_date'])

In [72]:
df

                 title prev_salary   first_name last_hire_date
0   Assistant Engineer  57317.5736         Arco     1985-02-02
1   Assistant Engineer  57317.5736       Selwyn     1985-02-02
2             Engineer  59602.7378        Taizo     1985-02-01
3              Manager  77723.6667        Isamu     1985-01-14
4      Senior Engineer  70823.4376        Arvin     1985-02-01
5      Senior Engineer  70823.4376         Gian     1985-02-01
6      Senior Engineer  70823.4376       Jayesh     1985-02-01
7      Senior Engineer  70823.4376       Kannan     1985-02-01
8      Senior Engineer  70823.4376         Mona     1985-02-01
9      Senior Engineer  70823.4376       Poorav     1985-02-01
10     Senior Engineer  70823.4376      Zdislav     1985-02-01
11        Senior Staff  80706.4959         Ebru     1985-01-01
12        Senior Staff  80706.4959    Margareta     1985-01-01
13               Staff  67330.6652         Arie     1985-01-01
14               Staff  67330.6652  Przemyslawa     1985-01-01
15               Staff  67330.6652      Shirish     1985-01-01
16               Staff  67330.6652        Tonny     1985-01-01
17    Technique Leader  67506.5903     DeForest     1985-01-01
18    Technique Leader  67506.5903    Krassimir     1985-01-01
19    Technique Leader  67506.5903    Peternela     1985-01-01

7. **Використання NTILE**
    
    Розподіліть зазначених співробітників на 3 групи за розміром їх поточної зарплати. Виведіть `emp_no`, `first_name`, `last_name`, зарплату та номер групи для кожного з них.
    
    `emp_no` співробітників, зарплати яких будемо досліджувати: `419748, 496734, 264134, 209076, 86631, 456171, 16887, 230255, 246465, 420097, 44362, 280370, 479975, 433320, 473949`

In [74]:
cursor = con.cursor()

query = """
WITH SelectedEmployees AS (
    SELECT
        e.emp_no,
        e.first_name,
        e.last_name,
        s.salary
    FROM
        employees e
    JOIN
        salaries s ON e.emp_no = s.emp_no
    WHERE
        e.emp_no IN (419748, 496734, 264134, 209076, 86631, 456171, 16887, 230255, 246465, 420097, 44362, 280370, 479975, 433320, 473949) AND
        s.to_date = '9999-01-01'
)

SELECT
    emp_no,
    first_name,
    last_name,
    salary,
    NTILE(3) OVER (ORDER BY salary DESC) as salary_group
FROM
    SelectedEmployees;

"""

cursor.execute(query)

results = cursor.fetchall()

cursor.close()

df = pd.DataFrame(results, columns=['emp_no', 'first_name', 'last_name', 'salary', 'salary_group'])

In [75]:
df

    emp_no first_name last_name  salary  salary_group
0   419748    Jixiang   Rindone  140784             1
1   496734   Dayanand    Morrey  136130             1
2   264134     Reuven    Uludag  134570             1
3   209076       Moon     Uhrik  133712             1
4    86631    Tristan     Isaac  133038             1
5   456171     Xuejun  Papsdorf  130010             2
6    16887   Bernardo  Sinitsyn  129036             2
7   230255      Ennio     Lorcy  128018             2
8   246465    Apostol    Leuchs  127924             2
9   420097      Aimee   Stifter  126885             2
10   44362     Manton     Kitai  126640             3
11  280370     Mayuko     Vesel  126629             3
12  479975   Kazuhiro      Pews  126163             3
13  433320    Gunilla  Takkinen  125600             3
14  473949    Pantung     Picht  124950             3

In [76]:
con.close()